### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by dianashk**
- need spec revision number
- need license so everyone is comfortable adopting the spec
- move `Feature` address parts into `address` scope

### CODE REVIEW

**Comment by yohanboniface** [comment]
Hi @dianashk and thanks for the PR :)
Sorry for the lag, I was travelling.

> need spec revision number

Good point!

> need license so everyone is comfortable adopting the spec

Good point! I would go for CC0, what do you think?

> move Feature address parts into address scope

Do you mean we should have both `address` namespace, and `geocoding` as discussed in #4 ?

**Comment by dianashk** [comment]
- CC0 works
- I was suggesting both `geocoding` and `address` namespaces. Just did the pull request off `master` in case your other branch was going to change still.

**Comment by yohanboniface** [comment]
Can you split the address suggestion from the other two changes? so we can merge those, while we need a bit more discussion to get consensus around `address` namespace ;)

**Comment by dianashk** [comment]
Done. :grinning:

**Comment by yohanboniface** [comment]
:)

**Comment by yohanboniface** [comment]
@dianashk can you also create another PR or issue about adding `address` namespace, so we can continue the discussion?

**Pull request merged**
